dist: trusty

language: node_js
node_js:
  - "12"

env:
  global:
    - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"

before_install:
  - npm install -g bower grunt-cli

install:
  - npm ci --quiet

script:
  - npm run-script travis_script

after_success:
  - npm run-script travis_after_success

notifications:
  irc:
  - "chat.freenode.net#wet-boew"
